### ISSUE TITLE
Archive/close https://gitlab-research.centralesupelec.fr/RiseClipseGroup

### ISSUE THREAD

**Issue by Sander3003** [riseclipse/riseclipse-developer#46]
In order to prevent confusion, please make sure that everyone know here to go for latest code and where to contribute.

If https://gitlab-research.centralesupelec.fr/RiseClipseGroup is never used anylonger, my suggestion is to remove or archive it.

**Comment by marcadetd** [comment]
Old RiseClipse projects at https://gitlab-research.centralesupelec.fr/RiseClipseGroup have been archived
